import type { BlockStyles, BoxStyleProps, TextStyleProps } from './types';

export const DEFAULT_STYLES: BlockStyles = {
  h1: { bold: true, marginBottom: 1, color: '#f74cc7ff' },
  h2: { bold: true, marginBottom: 1, color: '#326cfcff' },
  h3: { bold: true, color: '#24ffedff' },
  h4: { bold: true, color: '#e29418ff' },
  h5: { bold: true, color: '#9fc214ff' },
  h6: { bold: true, dimColor: true, color: '#88eb2bff' },
  paragraph: {},
  blockquote: {
    paddingLeft: 1,
    dimColor: true,
    borderTop: false,
    borderBottom: false,
    borderRight: false,
    borderStyle: 'single',
    borderDimColor: true,
  },
  code: { marginTop: 1 },
  codespan: { dimColor: true },
  list: {},
  listItem: { bullet: '●', paddingLeft: 2 },
  hr: { char: '─', width: 40, dimColor: true },
  link: { color: '#343afcff', underline: true },
  strong: { bold: true },
  em: { italic: true },
  del: { strikethrough: true, dimColor: true },
  image: { color: 'blue' },
  table: {},
  tableCell: { paddingRight: 2 },
};

export const TEXT_STYLE_KEYS: (keyof TextStyleProps)[] = [
  'color',
  'backgroundColor',
  'dimColor',
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'inverse',
  'wrap',
];

export const BOX_STYLE_KEYS: (keyof BoxStyleProps)[] = [
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'paddingBottom',
  'padding',
  'paddingX',
  'paddingY',
  'marginLeft',
  'marginRight',
  'marginTop',
  'marginBottom',
  'margin',
  'marginX',
  'marginY',
  'borderStyle',
  'borderColor',
  'borderTop',
  'borderBottom',
  'borderLeft',
  'borderRight',
  'borderDimColor',
  'borderTopColor',
  'borderBottomColor',
  'borderLeftColor',
  'borderRightColor',
  'borderTopDimColor',
  'borderBottomDimColor',
  'borderLeftDimColor',
  'borderRightDimColor',
];
